package melee

// Item represents an ItemTypeID, used in slippi.ItemUpdate entries, which show which items are present on which frames.
type Item uint16

const (
	ItemCapsule                      Item = iota // 0x00
	ItemBox                                      // 0x01
	ItemBarrel                                   // 0x02
	ItemEgg                                      // 0x03
	ItemPartyBall                                // 0x04
	ItemBarrelCannon                             // 0x05
	ItemBobOmb                                   // 0x06
	ItemMrSaturn                                 // 0x07
	ItemHeartContainer                           // 0x08
	ItemMaximTomato                              // 0x09
	ItemStarman                                  // 0x0A
	ItemHomeRunBat                               // 0x0B
	ItemBeamSword                                // 0x0C
	ItemParasol                                  // 0x0D
	ItemGreenShell                               // 0x0E
	ItemRedShell                                 // 0x0F
	ItemRayGun                                   // 0x10
	ItemFreezie                                  // 0x11
	ItemFood                                     // 0x12
	ItemProximityMine                            // 0x13
	ItemFlipper                                  // 0x14
	ItemSuperScope                               // 0x15
	ItemStarRod                                  // 0x16
	ItemLipsStick                                // 0x17
	ItemFan                                      // 0x18
	ItemFireFlower                               // 0x19
	ItemSuperMushroom                            // 0x1A
	ItemMiniMushroom                             // 0x1B
	ItemUnused                                   // 0x1C
	ItemWarpStar                                 // 0x1D
	ItemScrewAttack                              // 0x1E
	ItemBunnyHood                                // 0x1F
	ItemMetalBox                                 // 0x20
	ItemCloakingDevice                           // 0x21
	ItemPokeBall                                 // 0x22
	ItemRayGunRecoilEffect                       // 0x23
	ItemStarRodStar                              // 0x24
	ItemLipsStickDust                            // 0x25
	ItemSuperScopeBeam                           // 0x26
	ItemRayGunBeam                               // 0x27
	ItemHammerHead                               // 0x28
	ItemFlower                                   // 0x29
	ItemYoshiEggEvent                            // 0x2A
	ItemGoomba                                   // 0x2B
	ItemRedead                                   // 0x2C
	ItemOctarok                                  // 0x2D
	ItemOttosea                                  // 0x2E
	ItemOctarokProjectile                        // 0x2F
	ItemMarioFire                                // 0x30
	ItemUnused2                                  // 0x31
	ItemKirbyCutterBeam                          // 0x32
	ItemKirbyHammer                              // 0x33
	ItemUnknown1                                 // 0x34
	ItemUnknown2                                 // 0x35
	ItemFoxLaser                                 // 0x36
	ItemFalcoLaser                               // 0x37
	ItemFoxShadow                                // 0x38
	ItemFalcoShadow                              // 0x39
	ItemLinkBomb                                 // 0x3A
	ItemYoungLinkBomb                            // 0x3B
	ItemLinkBoomerang                            // 0x3C
	ItemYoungLinkBoomerang                       // 0x3D
	ItemLinkHookshot                             // 0x3E
	ItemYoungLinkHookshot                        // 0x3F
	ItemArrow                                    // 0x40
	ItemFireArrow                                // 0x41
	ItemPKFire                                   // 0x42
	ItemPKFlash                                  // 0x43
	ItemPKFlash2                                 // 0x44
	ItemPKThunderPrimary                         // 0x45
	ItemPKThunder                                // 0x46
	ItemPKThunder2                               // 0x47
	ItemPKThunder3                               // 0x48
	ItemPKThunder4                               // 0x49
	ItemFoxBlaster                               // 0x4A
	ItemFalcoBlaster                             // 0x4B
	ItemLinkArrow                                // 0x4C
	ItemYoungLinkArrow                           // 0x4D
	ItemPKFlashExplosion                         // 0x4E
	ItemNeedleThrown                             // 0x4F
	ItemNeedle                                   // 0x50
	ItemPikachuThunder                           // 0x51
	ItemPichuThunder                             // 0x52
	ItemMarioCape                                // 0x53
	ItemDrMarioCape                              // 0x54
	ItemSheikSmoke                               // 0x55
	ItemYoshiEggThrown                           // 0x56
	ItemYoshiTongue                              // 0x57
	ItemYoshiDownBStar                           // 0x58
	ItemPikachuThunder2                          // 0x59
	ItemPikachuThunder3                          // 0x5A
	ItemPichuThunder2                            // 0x5B
	ItemPichuThunder3                            // 0x5C
	ItemSamusBomb                                // 0x5D
	ItemSamusChargeshot                          // 0x5E
	ItemMissile                                  // 0x5F
	ItemGrappleBeam                              // 0x60
	ItemSheikChain                               // 0x61
	ItemUnknown3                                 // 0x62
	ItemTurnip                                   // 0x63
	ItemBowserFlame                              // 0x64
	ItemNessBat                                  // 0x65
	ItemNessYoyo                                 // 0x66
	ItemPeachParasol                             // 0x67
	ItemPeachToad                                // 0x68
	ItemLuigiFire                                // 0x69
	ItemIceClimbersIce                           // 0x6A
	ItemIceClimbersBlizzard                      // 0x6B
	ItemZeldaFire                                // 0x6C
	ItemZeldaFireExplosion                       // 0x6D
	ItemUnknown4                                 // 0x6E
	ItemPeachToadSpore                           // 0x6F
	ItemMewtwoShadowball                         // 0x70
	ItemIceClimbersUpB                           // 0x71
	ItemPesticide                                // 0x72
	ItemManhole                                  // 0x73
	ItemGameAndWatchFire                         // 0x74
	ItemParashute                                // 0x75
	ItemTurtle                                   // 0x76
	ItemSperky                                   // 0x77
	ItemJudge                                    // 0x78
	ItemUnknown5                                 // 0x79
	ItemSausage                                  // 0x7A
	ItemYoungLinkMilk                            // 0x7B
	ItemGameAndWatchFFirefighter                 // 0x7C
	ItemMasterHandLaser                          // 0x7D
	ItemMasterHandBullet                         // 0x7E
	ItemCrazyHandLaser                           // 0x7F
	ItemCrazyHandBullet                          // 0x80
	ItemCrazyHandsBomb                           // 0x81
	ItemKirbyCopyMarioFire                       // 0x82
	ItemKirbyCopyDrMarioCapsule                  // 0x83
	ItemKirbyCopyLuigiFire                       // 0x84
	ItemKirbyCopyIceClimbersIceCube              // 0x85
	ItemKirbyCopyPeachToad                       // 0x86
	ItemKirbyCopyToadsSpore                      // 0x87
	ItemKirbyCopyFoxLaser                        // 0x88
	ItemKirbyCopyFalcoLaser                      // 0x89
	ItemKirbyCopyFoxBlaster                      // 0x8A
	ItemKirbyCopyFalcoBlaster                    // 0x8B
	ItemKirbyCopyLinkArrow                       // 0x8C
	ItemKirbyCopyYoungLinkArrow                  // 0x8D
	ItemKirbyCopyLinkArrow2                      // 0x8E
	ItemKirbyCopyYoungLinkArrow2                 // 0x8F
	ItemKirbyCopyMewtwoShadowball                // 0x90
	ItemKirbyCopyPKFlash                         // 0x91
	ItemKirbyCopyPKFlashExplosion                // 0x92
	ItemKirbyCopyPikachuThunder                  // 0x93
	ItemKirbyCopyPikachuThunder2                 // 0x94
	ItemKirbyCopyPichuThunder                    // 0x95
	ItemKirbyCopyPichuThunder2                   // 0x96
	ItemKirbyCopySamusChargeshot                 // 0x97
	ItemKirbyCopySheiksNeedleThrown              // 0x98
	ItemKirbyCopySheiksNeedleGround              // 0x99
	ItemKirbyCopyBowserFlame                     // 0x9A
	ItemKirbyCopyGameAndWatchSausage             // 0x9B
	ItemUnique1                                  // 0x9C
	ItemYoshiTongue2                             // 0x9D
	ItemUnique2                                  // 0x9E
	ItemCoin                                     // 0x9F
	ItemUnique3                                  // 0xA0
	ItemRandomPokemonvalue                       // 0xA0
	ItemGoldeen                                  // 0xA1
	ItemChicorita                                // 0xA2
	ItemSnorlax                                  // 0xA3
	ItemBlastoise                                // 0xA4
	ItemWeezing                                  // 0xA5
	ItemCharizard                                // 0xA6
	ItemMoltres                                  // 0xA7
	ItemZapdos                                   // 0xA8
	ItemArticuno                                 // 0xA9
	ItemWobbuffet                                // 0xAA
	ItemScizor                                   // 0xAB
	ItemUnown                                    // 0xAC
	ItemEntei                                    // 0xAD
	ItemRaikou                                   // 0xAE
	ItemSuicune                                  // 0xAF
	ItemBellossom                                // 0xB0
	ItemElectrode                                // 0xB1
	ItemLugia                                    // 0xB2
	ItemHoOh                                     // 0xB3
	ItemDitto                                    // 0xB4
	ItemClefairy                                 // 0xB5
	ItemTogepi                                   // 0xB6
	ItemMew                                      // 0xB7
	ItemCelebi                                   // 0xB8
	ItemStaryu                                   // 0xB9
	ItemChansey                                  // 0xBA
	ItemPorygon2                                 // 0xBB
	ItemCyndaquil                                // 0xBC
	ItemMarill                                   // 0xBD
	ItemVenusaur                                 // 0xBE
	ItemChicoritaLeaf                            // 0xBF
	ItemBlastoiseWater                           // 0xC0
	ItemWeezingGas                               // 0xC1
	ItemWeezingGas2                              // 0xC2
	ItemCharizardBreath                          // 0xC3
	ItemCharizardBreath2                         // 0xC4
	ItemCharizardBreath3                         // 0xC5
	ItemCharizardBreath4                         // 0xC6
	ItemMiniUnowns                               // 0xC7
	ItemLugiaAeroblast                           // 0xC8
	ItemLugiaAeroblast2                          // 0xC9
	ItemLugiaAeroblast3                          // 0xCA
	ItemHoOhFlame                                // 0xCB
	ItemStaryuStar                               // 0xCC
	ItemHealingEgg                               // 0xCD
	ItemCyndaquilFire                            // 0xCE
	ItemUnknown6                                 // 0xCF
	ItemOldGoombaMonster                         // 0xD0
	ItemTargetMonster                            // 0xD1
	ItemShyguyMonster                            // 0xD2
	ItemKoopaGreenMonster                        // 0xD3
	ItemKoopaRedMonster                          // 0xD4
	ItemLikelileMonster                          // 0xD5
	ItemOldRedeadInvalidMonster                  // 0xD6
	ItemOldOctorokInvalidMonster                 // 0xD7
	ItemOldOttoseaMonster                        // 0xD8
	ItemWhiteBearMonster                         // 0xD9
	ItemKlapMonster                              // 0xDA
	ItemGreenShellMonster                        // 0xDB
	ItemRedShellMonster                          // 0xDC
	ItemTingle                                   // 0xDD
	ItemInvalid1                                 // 0xDE
	ItemInvalid2                                 // 0xDF
	ItemInvalid3                                 // 0xE0
	ItemApple                                    // 0xE1
	ItemHealingApple                             // 0xE2
	ItemInvalid4                                 // 0xE3
	ItemInvalid5                                 // 0xE4
	ItemInvalid6                                 // 0xE5
	ItemToolFlatzone                             // 0xE6
	ItemInvalid7                                 // 0xE7
	ItemInvalid8                                 // 0xE8
	ItemBirdo                                    // 0xE9
	ItemArwingLaser                              // 0xEA
	ItemGreatFoxLaser                            // 0xEB
	ItemBirdoEgg                                 // 0xEC
)
